"""Add Game schema

Revision ID: 5a95766c17f7
Revises: 046d5556acb8
Create Date: 2025-01-06 13:43:30.833553

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a95766c17f7"
down_revision: Union[str, None] = "046d5556acb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("match", sa.Column("game_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "match", "game", ["game_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_column("match", "game_id")
    op.drop_table("game")
    # ### end Alembic commands ###
